# https://taskfile.dev

version: '3'

env:
  CGO_ENABLED: '0'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: build

  get-deps:
    cmds:
      - go get ./...
    silent: true

  test:
    cmds:
      - task: get-deps
      - go test ./...

  build:
    cmds:
      - task: get-deps
      - '[ -d ./dist ] || mkdir dist'
      - go build -o dist/gh-notifications ./cmd/notifications

  dockerized-build:
    cmds:
      - '[ -d ./dist ] || mkdir dist'
      - 'docker run -v "$(pwd):$(pwd)" -w "$(pwd)" golang:alpine sh -c "go get ./...; go build -o dist/gh-notifications ./cmd/notifications"'